import {
  Home,
  Search,
  Calendar,
  Bell,
  Folder,
  Trash2,
  TicketCheckIcon,
  PlusCircle
} from "lucide-react";

export const SIDE_MENU_DATA = [
  {
    id: "01",
    title: "Home",
    url: "/student/dashboard",
    icon: Home,
  },
  { id: "02",
    title: "Create",
    url: "#",
    icon: PlusCircle,
  },
  { id: "03",
    title: "Search",
    url: "#",
    icon: Search,
  },
  { id: "04",
    title: "Completed",
    url: "#",
    icon: TicketCheckIcon,
  },
  { id: "05",
    title: "Calendar",
    url: "#",
    icon: Calendar,
  },
  { id: "06",
    title: "Notifications",
    url: "#",
    icon: Bell,
  },
  { id: "07",
    title: "Archives",
    url: "#",
    icon: Folder,
  },
  { id: "08",
    title: "Trash",
    url: "/project/test-id",
    icon: Trash2,
  },
]

export const SIDE_MENU_DATA_SUPERVISOR = [
  {
    id: "01",
    title: "Home",
    url: "#",
    icon: Home,
  },
  { id: "02",
    title: "Create",
    url: "#",
    icon: PlusCircle,
  },
  { id: "03",
    title: "Search",
    url: "#",
    icon: Search,
  },
  { id: "04",
    title: "Completed",
    url: "#",
    icon: TicketCheckIcon,
  },
  { id: "05",
    title: "Calendar",
    url: "#",
    icon: Calendar,
  },
  { id: "06",
    title: "Notifications",
    url: "#",
    icon: Bell,
  },
  { id: "07",
    title: "Archives",
    url: "#",
    icon: Folder,
  },
  { id: "08",
    title: "Trash",
    url: "#",
    icon: Trash2,
  },
]

export const SIDE_MENU_DATA_COORDINATOR = [
  {
    id: "01",
    title: "Home",
    url: "#",
    icon: Home,
  },
  { id: "02",
    title: "Create",
    url: "#",
    icon: PlusCircle,
  },
  { id: "03",
    title: "Search",
    url: "#",
    icon: Search,
  },
  { id: "04",
    title: "Completed",
    url: "#",
    icon: TicketCheckIcon,
  },
  { id: "05",
    title: "Calendar",
    url: "#",
    icon: Calendar,
  },
  { id: "06",
    title: "Notifications",
    url: "#",
    icon: Bell,
  },
  { id: "07",
    title: "Archives",
    url: "#",
    icon: Folder,
  },
  { id: "08",
    title: "Trash",
    url: "#",
    icon: Trash2,
  },
]

export const PRIORITY_DATA = [
  {
    id: "01",
    title: "Home",
    url: "#",
    //icon: Home,
  },

]

export const STUDENT_PROJECT_NAVBAR = [
  { title: "Overview", path: "" },
  { title: "Tasks", path: "tasks" },
  { title: "Team", path: "team" },
  { title: "Budget", path: "budget" },
];


export const SUPERVISOR_PROJECT_NAVBAR = [
  { title: "Overview", url: "/project/test-id" },
  { title: "Tasks", url: "/project/test-id/tasks" },
  { title: "Assignments", url: "/project/test-id/assignments" },
  { title: "Team", url: "/project/test-id/team" },
  { title: "Announcements", url: "/project/test-id/announcements" },
];